### ISSUE TITLE
Custom ViewHelper uses PHPRenderer instead of TwigRenderer

### ISSUE THREAD

**Issue by exptom** [kokspflanze/ZfcTwig#13]
I am having this exact problem: https://github.com/ZF-Commons/ZfcTwig/issues/103 in the latest 1.4.2 version. 

In summary when trying to render a twig template partial inside a custom view helper it is not rendered because the PHPRenderer is injected into the customer view helper rather than the TwigRenderer.

Any ideas how to fix?

**Comment by kokspflanze** [comment]
@exptom i will check what i can do

**Comment by kokspflanze** [comment]
hi @exptom i tested that case and for me it works following

````php
return [
    'view_helpers' => [
        'aliases' => [
            'sidebarWidget' => Helper\SideBarWidget::class,
        ],
        'factories' => [
            Helper\SideBarWidget::class => InvokableFactory::class,
        ],
    ],
    'zfctwig' => [
        'helper_manager' => [
            'configs' => [
                HelperConfig::class
            ],
            'aliases' => [
                'sidebarWidget' => Helper\SideBarWidget::class,
            ],
            'factories' => [
                Helper\SideBarWidget::class => InvokableFactory::class,
            ],
        ],
    ],
];
````

my sidebar template looks like following

````php
{{ "now"|date('y-m-d') }}
````

hope that help you, if not i need more informations.

**Comment by exptom** [comment]
@kokspflanze Thanks for the example, I realise that I had not understood the helper_manager config correctly and it is working now. Thanks for your help.
