### ISSUE TITLE
How do we disable cache?

### ISSUE THREAD

**Issue by Saeven** [kokspflanze/ZfcTwig#20]
Thank you for this excellent fork.

**Comment by exptom** [comment]
@Saeven 

In any of your module config files or perhaps `config\autoload\local.php` (specific file is up to you and dependent on how you implement dev/live environments):
```
[
    'zfctwig' => [
        'environment_options' => [
            'cache' => false
        ]
]
```

You can set the other twig environment options in that array also as per [twig docs](https://twig.symfony.com/doc/1.x/api.html#environment-options)

**Comment by kokspflanze** [comment]
@exptom thanks=)
i think that should help

**Comment by Saeven** [comment]
Thank you - I had tried that and was misled by the result to believe it didn't work.  Turns out I'm being kicked in the teeth by gettext cache, not twig cache.  Whole new problem.  Thanks for your help.
