### ISSUE TITLE
Thank you!  Macros?

### ISSUE THREAD

**Issue by Saeven** [kokspflanze/ZfcTwig#26]
First - thank you for keeping zfc-twig alive. This thing is at lifeblood level for ZF apps in my opinion!

I was trying to use macros today (on these versions):

```
$ composer show | grep twig
kokspflanze/zfc-twig                         2.3.1              Zend Framework Module that provides a Twig rendering strategy and extensions to render actions or trigger events from your templates
twig/extensions                              v1.5.4             Common additional features for Twig that do not directly belong in core
twig/twig                                    v2.9.0             Twig, the flexible, fast, and secure template language for PHP
```

It doesn't complain about parsing the macro, only about using it.

    {% macro helloWorld() %}
       <div>Hello World</div>
    {% endmacro %}
    
    {{ helloWorld() }}

Results in 

`Fatal error: Uncaught Twig\Error\SyntaxError: Unknown "helloWorld" function`

Any quick tips on where I should look?

Thanks again.
Alex

**Comment by kokspflanze** [comment]
no problem to keep it uptodate=]

sry never worked with macros, have to check it self but can take bit time=[

**Comment by kokspflanze** [comment]
sry for the late answer=(.

you have to import the macros.

hello.twig
````twig
{% macro helloWorld() %}
    <div>Hello World</div>
{% endmacro %}
````

config
````php
    'view_manager' => [
        'template_map' => [
            'hello.twig' => __DIR__ . '/../view/helper/hello.twig',
        ],
    ],
````

view stuff
````twig
{% import "hello.twig" as forms %}
{{ forms.helloWorld() }}
````

works fine=)
