### ISSUE TITLE
Not ZF2 compatible

### ISSUE THREAD

**Issue by sattes-faction** [kokspflanze/ZfcTwig#33]
Hi,
first, thanks for your efforts! The README says it's working with ZF2, but composer.json requires zend-mvc version 3.

**Comment by kokspflanze** [comment]
hi, yes thats correct, with v2 i dropped zf2 support.
but you can still use 1.4.4 this support mvc v2

https://github.com/kokspflanze/ZfcTwig/blob/1.4.4/composer.json#L42

**Comment by sattes-faction** [comment]
Ok, I see - thanks for clarification!
