### ISSUE TITLE
Laminas support with Twig v1.x

### ISSUE THREAD

**Issue by 0nua** [kokspflanze/ZfcTwig#39]
Hi! Thank a lot for your work! I am using this fork v1.4.3 in legacy project on ZF 3 with twig v1.x. Is it possible migrate v1.4 to Laminas? There are a lot of problems in twig migration from 1.x to 3.x, so it is cause why I can not use your last v4 package version.

**Comment by kokspflanze** [comment]
hi, i will check it, if i can support all twig versions.

i try to check it next week, hope thats okay=]

**Comment by 0nua** [comment]
Yep, of cause it is okay! Thank you! 👍

**Comment by kokspflanze** [comment]
the interfaces of v1 and v3 are  not same, so its not realy easy.

whats your problem to migrate to twig v3?

**Comment by 0nua** [comment]
Ок, thank you for help) Project has a lot of custom rules in twig environment and, as usual it happens, we have not enouth time for upgrading twig, but looks like it is nessary action.
