### ISSUE TITLE
Server 500 after updating twig/twig from v3.11 to v3.12 (released 4 days ago: 2024-8-29)

### ISSUE THREAD

**Issue by criterion9** [kokspflanze/ZfcTwig#47]
There appears to be a change in how the environment is setup with twig/twig's change from v3.11 to v3.12 which throws errors such as:  

- "The` ZfcTwig\\Twig\\Extension extension is not enabled." 

and 

- "Failed` to create closure from callable: function `"$this->env->getExtension("ZfcTwig\\Twig\\Extension")->getRenderer()->plugin("translate")->__invoke"` not found or invalid function name"

Restricting twig/twig to v3.11 in composer.json eliminates the errors.

**Comment by kokspflanze** [comment]
Hello @criterion9 im on the error.
