### ISSUE TITLE
Why not provide basic templates and extensions?

### ISSUE THREAD

**Issue by celtic34fr** [kokspflanze/ZfcTwig#9]
Hi, 
I use Twig in my personal project GraphicObjectTemplating (ZF2/ZF3).
Giving access to TWIG under ZF2 / ZF3 is interesting, but having an adaptation of the basic templates would be more useful.
If this can help you, I would have both extensions and basic templates to offer you
- layout/layout, error/index, error/404, application/index/index (templates),
- intanceOf, typeOf (test extensions),
- getclass, gettype, arrayexception (for error/index template), checkBoolean, substr, strpos, instring (function extensions),
- contains (subchain is in string), update (update of table by key / value), unset (deletion occurance in array by key) (filter extension)

If you are interested, I can send you the ZF3 sources by email at your request, not all in my project on github (celti34fr / graphic-object-templating)

I found in the TWIG repository a tag refused by Fabien POTENCIER: switch/case that I adapted, I can also provide you.

Gilbert ARMENGAUD
celtic34fr
gilbert.armengaud@gmail.com
(Béziers - Hérault - Occitanie - France)

**Comment by kokspflanze** [comment]
hi @celtic34fr about the layout and extensions we can maybe create a extension module, which has all of these parts.

atm i see the current version more as a clean basic way, with just the main twig parts.

what you think about that?

**Comment by celtic34fr** [comment]
Hi, 

I just thought about providing all the useful templates and extensions for anyone wanting to use Twig in a ZF project. This is for not having a mixed code on the site: the error screens in phtml and the rest in TWIG.

My purpose is not to create a new extension in order to provide the basic templates: layout, error/404, error/index. Moreover, I create an extension but not with the same goal: to provide through an object framework another way to build and interact with web pages: GraphicObjectTemplating. I will attach the base templates as well as the TWIG extension required for their display.

**Comment by kokspflanze** [comment]
if you want you can create a PR with these changes for `error/404` and `error/index` with the extensions

**Comment by celtic34fr** [comment]
So, I'll take time the next weekend to do it, while respecting your logic of organization of the module

**Comment by bupy7** [comment]
@celtic34fr `instanceof`:

```php
<?php

namespace ExTwig\Extension;

use Twig_Extension;
use Twig_SimpleFunction;
use Twig_SimpleTest;

class ClassExtension extends Twig_Extension
{
    /**
     * {@inheritDoc}
     */
    public function getName()
    {
        return 'extwig-class-extension';
    }

    /**
     * {@inheritDoc}
     */
    public function getFunctions()
    {
        return [
            'get_class' => new Twig_SimpleFunction('get_class', [$this, 'getClassName']),
        ];
    }

    /**
     * {@inheritDoc}
     */
    public function getTests()
    {
        return [
            'instanceof' => new Twig_SimpleTest('instanceof', [$this, 'isInstanceOf']),
        ];
    }

    /**
     * @param object $object
     * @return string
     */
    public function getClassName($object)
    {
        return get_class($object);
    }

    /**
     * @param object|string $actualClass
     * @param object|string $expectClass
     * @return boolean
     */
    public function isInstanceOf($actualClass, $expectClass)
    {
        return $actualClass instanceof $expectClass;
    }
}
```
